[wokwi]
version = 1
elf = ".pio/build/uno/firmware.elf"
firmware = ".pio/build/uno/firmware.hex"

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"